### ISSUE TITLE
release/public-v8: Out of Bound Exception in GFSPOST.F (tpause subroutine)

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/UPP#91]
When I run post compiled with a flag that checks out-of-bound exceptions, I get the following runtime error:
```
At line 459 of file /home/dusan/simple-ufs/src/post/sorc/ncep_post.fd/GFSPOST.F
Fortran runtime error: Index '65' of dimension 1 of array 'u' above upper bound of 64

Error termination. Backtrace:
#0  0x902e2c in tpause_
        at /home/dusan/simple-ufs/src/post/sorc/ncep_post.fd/GFSPOST.F:460
#1  0xa87d7f in miscln_
        at /home/dusan/simple-ufs/src/post/sorc/ncep_post.fd/MISCLN.f:443
#2  0x7453cc in process_
        at /home/dusan/simple-ufs/src/post/sorc/ncep_post.fd/PROCESS.f:111
#3  0x4951f3 in wrfpost
        at /home/dusan/simple-ufs/src/post/sorc/ncep_post.fd/WRFPOST.f:869
#4  0x495bcd in main
        at /home/dusan/simple-ufs/src/post/sorc/ncep_post.fd/WRFPOST.f:134

```

**Comment by fossell** [comment]
@DusanJovic-NOAA We just encountered this bug as well but have not submitted an issue yet.  It's pops up in processing other models as well.  Just fyi - we have uncovered other bugs in debug mode as well (mostly unintialized variables), I'm not sure they will crop up for UFS testing, but please let us know and we can see if we have a solution already in DTC_post branch.

@WenMeng-NOAA - This TPAUSE bug needs to be resolved, something in computing the trop levels tries to access k+1 vertical levels but this goes above the number of model levels.  @hertneky discovered this in our pre-release testing for WRF, but it impacts other models as well and we are unclear of total impact so we need to defer to EMC for suggested bug fix.  @hertneky might be able to provide more detail if needed.

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA , @fossell , @hertneky Thanks for catching this bug. Can any one submit a change so that I can test in UPP regression tests for any impacts on other models.

**Comment by DusanJovic-NOAA** [comment]
I'm getting this syntax error when I build EMC_post (public release branch) using Intel compiler with debug flags:

```
/scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/sufs/simple-ufs-aero/src/post/sorc/ncep_post.fd/GFSPOST.F(221): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is
 of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [L2]
      call rsearch1(km,p,1,pvpb(k),l1)
-----------^
/scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/sufs/simple-ufs-aero/src/post/sorc/ncep_post.fd/GFSPOST.F(222): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is
 of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [L2]
      call rsearch1(km,p,1,pvpt(k),l2)
-----------^
/scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/sufs/simple-ufs-aero/src/post/sorc/ncep_post.fd/GFSPOST.F(231): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is
 of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [L2]
            call rsearch1(km,p,1,p(lu)+pd,ld)
-----------------^
/scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/sufs/simple-ufs-aero/src/post/sorc/ncep_post.fd/GFSPOST.F(245): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is
 of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [L2]
            call rsearch1(km,p,1,p(lu)+pd,ld)
-----------------^
```
I don't know if this error is related to the above out-of-bounds issue (with GNU compiler).

**Comment by DusanJovic-NOAA** [comment]
@WenMeng-NOAA @fossell Any chance of merging your bug fixes related to the use of uninitialized variables. For example I'm getting this run-time error:
```
forrtl: severe (194): Run-Time Check Failure. The variable 'initpost_gfs_netcdf_$NFHOUR' is being used in '/scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/simple-ufs/src/post/sorc/ncep_post.fd/INITPOST_GFS_NETCDF.f(576,7)' without being defined
Image              PC                Routine            Line        Source             
ufs_post           00000000004F4680  initpost_gfs_netc         576  INITPOST_GFS_NETCDF.f
ufs_post           00000000005E9FBD  MAIN__                    725  WRFPOST.f
ufs_post           000000000040775E  Unknown               Unknown  Unknown
libc-2.17.so       00002B7276724505  __libc_start_main     Unknown  Unknown
ufs_post           0000000000407669  Unknown               Unknown  Unknown
```
which I'm sure you already have a fix for.

**Comment by DusanJovic-NOAA** [comment]
This change:
```
$ git diff
diff --git a/sorc/ncep_post.fd/GFSPOST.F b/sorc/ncep_post.fd/GFSPOST.F
index 823aaf7..ae43a9f 100644
--- a/sorc/ncep_post.fd/GFSPOST.F
+++ b/sorc/ncep_post.fd/GFSPOST.F
@@ -419,7 +419,7 @@ end subroutine
     integer klim(2),k,kd,ktp
 ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 !  find tropopause level
-    call rsearch1(km-2,p(2),2,ptplim(1),klim(1))
+    call rsearch1(km-2,p(2),2,ptplim,klim)
     klim(1)=klim(1)+1
     klim(2)=klim(2)+2
     ! klim(1) > klim(2) or loops does not run ; klim(2) has a
@@ -519,7 +519,7 @@ end subroutine
     real spd(km),spdmw,wmw,dhd,dhu,shrd,shru,dhmw,ub,vb,spdb
 ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 !  find maximum wind level
-    call rsearch1(km,p(1),2,pmwlim(1),klim(1))
+    call rsearch1(km,p(1),2,pmwlim,klim)
 !    klim(1)=klim(1)+1
     klim(2)=klim(2)+1
 !    spd(klim(1):klim(2))=sqrt(u(klim(1):klim(2))**2+v(klim(1):klim(2))**2)
```
seems to fix the first issue:
```
At line 459 of file /home/dusan/simple-ufs/src/post/sorc/ncep_post.fd/GFSPOST.F
Fortran runtime error: Index '65' of dimension 1 of array 'u' above upper bound of 64
```

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Thanks for the fix. I will test your fix for lines:
call rsearch1(km-2,p(2),2,ptplim(1),klim(1))
call rsearch1(km,p(1),2,pmwlim(1),klim(1))

**Comment by fossell** [comment]
@DusanJovic-NOAA - After reviewing, I don't think our uninitialized variables fixes will help in this case since they are for WRF model processing in the INITPOST.F routine, but you can look at #72 if that's helpful.  There are likely plenty more in the code, we have not had time to identify all debug issues at this time.
